### PR TITLE
2 0 for real

### LINKED ISSUE #136: croaring 2.0 yanked?
Hi,
It seems like the officially tagged release is 2.0 while this is the situation on crates.io:

image

Can someone from the project provide a clarification of the state of 2.0, is it brandishing a croaring 3.0 / 4.0 and what is exactly the release status.

Also, I personally think it would greatly add / improve clarity of the versioning would follow croraring major versioning at the least so that users clearly understand what they are getting...

### PR DESCRIPTION
**Pull request by Dr-Emann**
Add some tests which will fail until we get a 4.0.1 of CRoaring. Don't merge until we update again once CRoaring is fixed.

Also, include the matching CRoaring version in the readme and some clarification on versioning, this will hopefully help clarify somewhat the questions raised in #136. Link to the rendered added section: https://github.com/Dr-Emann/croaring-rs/blob/2_0_for_real/README.md#croaring-version

Fixes #136

### CODE REVIEW

**Comment by Dr-Emann** [comment]
@saulius, what are your thoughts on matching the CRoaring versioning exactly (bumping croaring-sys to `4.0.0`) for `croaring-sys`, at least the major versions could probably match, any major version bump for them is almost guaranteed to be a major version bump for it, and I don't foresee any reason we'd make breaking changes to the sys crate other than updating to a new CRoaring version.

**Comment by saulius** [comment]
@Dr-Emann I'd agree for the `croaring-sys` to match the version. For the `croaring` crate I'd say no, as it implies we should have feature parity with `CRoaring` which I guess we cannot commit to. Also if there's a bug in Rust code, we'll have to break the version pin to release a bugfix.

**Comment by Dr-Emann** [comment]
Also noticed some functions which should have `must_use` were missing it, so I went through and checked every function.

**Comment by saulius** [comment]
Great work @Dr-Emann, thanks for shipping it!

**Pull request merged**
