### PR TITLE
wip: trying to debug windows CI failures

### PR DESCRIPTION
**Pull request by Dr-Emann**

### CODE REVIEW

**Comment by Dr-Emann** [comment]
@lemire, It does appear to reproduce with c only, building [this file](https://github.com/Dr-Emann/croaring-rs/blob/debug_win_ci/roaring_fast_or.c) with msvc cl: see the "msvc c roaring" step of [this job](https://github.com/RoaringBitmap/croaring-rs/actions/runs/7649855156/job/20844971113?pr=128) (which is set to continue on error for that step).

It's built with https://github.com/Dr-Emann/croaring-rs/blob/debug_win_ci/.github/workflows/rust.yml#L53-L60, based on the flags/environment rust is compiling the c code with

> running
> Hardware support: 0x1
> Going to or many
> -1073741795

(where -1073741795 is 0xC000001D (STATUS_ILLEGAL_INSTRUCTION)).

croaring_hardware_support() = 0x1 doesn't appear to indicate AVX512 is the problem.

The issues began (with I believe no meaningful changes in CRoaring/croaring-rs) sometime between 3 months ago and 2 weeks ago
image

I have no idea why we don't see any issues in CRoaring itself

**Comment by Dr-Emann** [comment]
Given no code changes between croaring/croaring-rs, I'm thinking it's the MSVC version bump from [17.7](https://github.com/actions/runner-images/blob/faac8776f4cfc45a36eb83ca68469defd6b0cafb/images/win/Windows2022-Readme.md?plain=1#L226) to [17.8](https://github.com/actions/runner-images/blob/d499bba673d88d0fc617ebb3d08ca473407c35b1/images/windows/Windows2022-Readme.md#L228) which occurred between the last working test vs the first failing one.

**Comment by Dr-Emann** [comment]
This feels awfully relevant: https://developercommunity.visualstudio.com/t/Invalid-AVX512-instructions-generated-wh/10521872

**Comment by Dr-Emann** [comment]
Also relevant, looks like if MSVC figures out we're going to avx512 in the function, it can use it anywhere. I don't see anywhere we could use any avx512 intrinsics in the avx2 code path though, from a somewhat close look:
https://developercommunity.visualstudio.com/t/Invalid-code-gen-when-using-AVX2-and-SSE/10527298

**Comment by lemire** [comment]
>  looks like if MSVC figures out we're going to avx512 in the function, it can use it anywhere.

I think we can disable AVX-512 code paths entirely (under Windows).

**Comment by Dr-Emann** [comment]
Looks like disabling AVX512 isn't enough, we have to disable AVX entirely 🫤

**Comment by lemire** [comment]
> Looks like disabling AVX512 isn't enough, we have to disable AVX entirely

It is certainly possible to have hardware lacking AVX instruction support. But we should handle this scenario.

You may have seen that CRoaring now effectively runs your small tests from the amalgamated files in CI, and it appears to work.

**Comment by lemire** [comment]
@Dr-Emann Can you review CI tests
https://github.com/RoaringBitmap/CRoaring/actions/runs/7670008347/job/20905194245

You can see that it is running the amalgamation tests which involve precisely the function you suggested. It is building it using the default Visual Studio 2022 provided by GitHub.

What are we missing?

**Comment by Dr-Emann** [comment]
@lemire: The difference appears to be in MSVC versions (or the cl versions? Don't really understand the VS/MSVC/cl.exe/etc version differences)

cmake seems to pick `MSVC\14.37.32822\bin\HostX64\x64\CL.exe`, and rust seems to pick `MSVC\14.38.33130\bin\HostX64\x64\cl.exe`. If I use the `14.37` cl, the compiled code works fine, if I use the `14.38` cl instead, I get the Illegal Instruction

**Comment by lemire** [comment]
@Dr-Emann I am updating to the very latest Visual Studio on my laptop.

**Comment by lemire** [comment]
But it is not going to be super useful because my laptop does support AVX instructions. :-/

**Comment by lemire** [comment]
@Dr-Emann 

vpxord is AVX512F + AVX512VL.

**Comment by lemire** [comment]
My best guess is that this code confuses Visual Studio into using AVX-512 throughout:

```C++
int bitset_container_compute_cardinality(const bitset_container_t *bitset) {
    int support = croaring_hardware_support();
#if CROARING_COMPILER_SUPPORTS_AVX512
    if( support & ROARING_SUPPORTS_AVX512 ) {
      return (int) avx512_vpopcount(
        (const __m512i *)bitset->words,
        BITSET_CONTAINER_SIZE_IN_WORDS / (WORDS_IN_AVX512_REG));
    } else
#endif // CROARING_COMPILER_SUPPORTS_AVX512
    if( support & ROARING_SUPPORTS_AVX2 ) {
      return (int) avx2_harley_seal_popcount256(
        (const __m256i *)bitset->words,
        BITSET_CONTAINER_SIZE_IN_WORDS / (WORDS_IN_AVX2_REG));
    } else {
      return _scalar_bitset_container_compute_cardinality(bitset);

    }
}
```

What confuses me is that you are say that disabling AVX-512 did not help.

**Comment by lemire** [comment]
@Dr-Emann Please review... https://github.com/RoaringBitmap/CRoaring/pull/579

If it makes sense to you, we shall try this approach. If it solves the issue, then we are lucky.

**Comment by Dr-Emann** [comment]
I'm fairly sure that when I tried with `CROARING_COMPILER_SUPPORTS_AVX512=0`, it didn't work, no.

I think there were two "bugs" I posted.

[The first](https://developercommunity.visualstudio.com/t/Invalid-AVX512-instructions-generated-wh/10521872) was acknowledged as a bug by microsoft, and it seemed to be that the compiler would insert avx512 instructions when only AVX2 was enabled (or maybe that the AVX2 intrinsics were producing avx512 instructions?), and was marked as `Fixed - Pending Release` almost a month ago.

[The second](https://developercommunity.visualstudio.com/t/Invalid-code-gen-when-using-AVX2-and-SSE/10527298) was closed as not a bug, where the compiler figured out that the codepath was going to use avx512 intrinsics in the same codepath, so optimized assuming it could use avx512.

I think we're hitting the first issue, not the second.

**Comment by lemire** [comment]
@Dr-Emann If you take my PR, the one where I move the AVX-512, and you use that in your rust binding, does it help?

**Comment by Dr-Emann** [comment]
Nope, it still ends up with avx512 instructions with that branch (even with `-DCROARING_COMPILER_SUPPORTS_AVX512=0`) when compiling with `MSVC 14.38`.

**Comment by lemire** [comment]
@Dr-Emann Hmmmm.... I don't know what else to do.

**Comment by Dr-Emann** [comment]
I really think it's just an MSVC bug that'll hopefully be fixed in 14.39. I think our only real options are:

* ignore it for now, hopefully it'll be fixed soon
* disable the avx2 path entirely if `defined( _MSC_VER ) && _MSC_VER >= 1938`

**Comment by lemire** [comment]
Disabling AVX seems extreme. I would happily disable AVX-512 under Windows if it were needed, but I feel uneasy about disabling AVX since almost all Windows machines that we care about have AVX2.

**Comment by Dr-Emann** [comment]
I really don't see any way around it for the versions of MSVC that has this bug, the alternative is miscompilation which will cause a crash.

Here's a godbolt link including only `CSA`, `popcount256`, and `avx2_harley_seal_popcount256`, and you can see the output includes a `vpxord` instruction, even though there's no mention of avx512 ANYWHERE, never mind in the same function: https://c.godbolt.org/z/d764KGWK1

And if you change back to MSVC 19.37 (still don't understand the versioning, why is it 14 some places and 19 elsewhere?), there's no vpxord instruction.

**Comment by yeastplume** [comment]
Seeing same issue, glad to see there's a thread here about this because I've been tearing my hair out over this for a couple of weeks now:

https://github.com/mimblewimble/grin-gui/issues/73#issuecomment-1905982066

**Comment by lemire** [comment]
@yeastplume 

I think that @Dr-Emann has demonstrated that it is a compiler bug.

**Comment by lemire** [comment]
@yeastplume For now, I recommend you just avoid the offending compiler version. If I were Microsoft, I would just patch it and make sure that the bug goes away.

I don't think we will do anything.

**Comment by yeastplume** [comment]
> @yeastplume For now, I recommend you just avoid the offending compiler version. If I were Microsoft, I would just patch it and make sure that the bug goes away.
> 
> I don't think we will do anything.

Yes, makes sense and thanks for your work tracking this down.

Slightly tangential, I guess, but does anyone have a quick pointer as to how to force github actions to use a particular compiler version?

**Comment by lemire** [comment]
>Slightly tangential, I guess, but does anyone have a quick pointer as to how to force github actions to use a particular compiler version? 

The current windows-latest runner should only have two versions installed, a very old one, and the very latest one, see the specs...

https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

I don't think it is possible to install another version of Visual Studio on the GitHub hosted runners.

So we have to wait for Microsoft to fix this.

**Comment by lemire** [comment]
See https://developercommunity.visualstudio.com/t/Code-gen-bug-uses-ymm16-register-for-AVX/10564317

**Comment by lemire** [comment]
@Dr-Emann Waiting for a fix from Microsoft did not help. They released 17.9 and it is the version we have in the GitHub runners, but the issue remains for us.

We need to change our code to try and fix this issue.

**Pull request closed without merging**
