### PR TITLE
Convert benchmarks to criterion

### PR DESCRIPTION
**Pull request by Dr-Emann**
Allow running benchmarks on stable, and with more rigor

### CODE REVIEW

**Comment by saulius** [comment]
Sounds good :+1:

**Review by saulius — APPROVED** [review]

**Comment by Dr-Emann** [comment]
I don't have permissions to merge

**Comment by saulius** [comment]
Sorry @Dr-Emann. After project transfer to RoaringBitmap org I still thankfully can merge, but cannot edit settings of the project anymore. @lemire can you help us? I'd suggest allowing Rust Roaring team to manage this or create a new team just for croaring-rs.

**Comment by lemire** [comment]
You should have full administrative access to this repository, including the right to grant access to others.

**Comment by lemire** [comment]
@saulius If you cannot give @Dr-Emann access, I can… but since this is your project, I’d rather you do it, obviously.

**Comment by saulius** [comment]
Thank you, @lemire. We need more maintainers for the project, as it seems there's some adoption.

**Pull request merged**
